<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_permission('view_reports');

$id = (int) ($_GET['id'] ?? 0);
$stmt = db()->prepare(
    "SELECT r.*, lr.request_code, lr.requesting_physician, lr.clinical_notes,
            p.patient_code, p.sex, p.birth_date, p.first_name, p.last_name, p.middle_name,
            ua.full_name AS approved_by_name, ur.full_name AS released_by_name
     FROM lab_results r
     JOIN lab_requests lr ON lr.id = r.lab_request_id
     JOIN patients p ON p.id = lr.patient_id
     LEFT JOIN users ua ON ua.id = r.approved_by
     LEFT JOIN users ur ON ur.id = r.released_by
     WHERE r.id = ?"
);
$stmt->execute([$id]);
$result = $stmt->fetch();
if (!$result) {
    flash('error', 'Report not found.');
    redirect('reports/index.php');
}

if (!in_array($result['status'], ['approved', 'reported', 'released'], true)) {
    flash('error', 'Report is only available after approval.');
    redirect('results/view.php?id=' . $id);
}

$values = db()->prepare(
    'SELECT rv.*, lt.test_code, lt.test_name, lt.unit
     FROM result_values rv
     JOIN lab_tests lt ON lt.id = rv.lab_test_id
     WHERE rv.lab_result_id = ?
     ORDER BY lt.test_code'
);
$values->execute([$id]);
$valueRows = $values->fetchAll();

$pageTitle = 'Report ' . $result['result_code'];
require __DIR__ . '/../includes/header.php';
?>
<div class="card" id="report-print">
    <h1>Laboratory Report</h1>
    <p><strong><?= e(app_config('lab_name')) ?></strong></p>
    <hr>
    <p>
        <strong>Patient:</strong> <?= e($result['last_name'] . ', ' . $result['first_name'] . ' ' . ($result['middle_name'] ?? '')) ?><br>
        <strong>Patient ID:</strong> <?= e($result['patient_code']) ?> |
        <strong>Sex:</strong> <?= e($result['sex']) ?> |
        <strong>Age:</strong> <?= patient_age($result['birth_date']) ?><br>
        <strong>Request:</strong> <?= e($result['request_code']) ?> |
        <strong>Result:</strong> <?= e($result['result_code']) ?> |
        <strong>Panel:</strong> <?= e($result['panel_code']) ?><br>
        <strong>Physician:</strong> <?= e($result['requesting_physician'] ?: '—') ?>
    </p>
    <table>
        <thead><tr><th>Test</th><th>Result</th><th>Unit</th><th>Flag</th></tr></thead>
        <tbody>
        <?php foreach ($valueRows as $v): ?>
            <tr>
                <td><?= e($v['test_name'] . ' (' . $v['test_code'] . ')') ?></td>
                <td><?= e((string) $v['numeric_value']) ?></td>
                <td><?= e($v['unit']) ?></td>
                <td>
                    <?php if ($v['is_critical']): ?>Critical<?php elseif ($v['is_out_of_range']): ?>Abnormal<?php else: ?>Normal<?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <p style="margin-top:1rem">
        Status: <strong><?= e($result['status']) ?></strong><br>
        Approved by: <?= e($result['approved_by_name'] ?: '—') ?> at <?= e($result['approved_at'] ?: '—') ?><br>
        Released by: <?= e($result['released_by_name'] ?: '—') ?> at <?= e($result['released_at'] ?: '—') ?>
    </p>
    <?php if ($result['ai_flagged']): ?>
        <p><em>Note: This result was reviewed with an AI anomaly warning present prior to approval.</em></p>
    <?php endif; ?>
    <p class="sub">This report was generated by the AI-Assisted Laboratory Information System. Clinical interpretation remains the responsibility of licensed laboratory personnel.</p>
</div>
<div class="actions">
    <button class="btn" type="button" onclick="window.print()">Print</button>
    <a class="btn btn-secondary" href="<?= e(base_url('results/view.php?id=' . $id)) ?>">Back to result</a>
</div>
<?php require __DIR__ . '/../includes/footer.php'; ?>
